### ISSUE TITLE
0.3.5 parser gives me OFX::UnsupportedFileError - works in 0.3.3

### ISSUE THREAD

**Issue by salex** [annacruz/ofx#96]
I've been using OFX for about 5 or 6 years. Same bank, same format.

I initially had some problem, think a BigDecimal error that I patched.

I'm using it in a Rails application that I'm trying to update.  My new approach is I download a QBO file from the bank and stuff it in a BankStatement model as a text field.

I was working with 0.3.3 using

```ruby
gem 'ofx' , '~> 0.3.3' , github: 'annacruz/ofx', branch: 'main'
``` 
In my gem file. I saw that the version was updates and then just did `gem 'ofx'` in the gem file and it bundled 0.3.5.  I swear it worked a few weeks ago but now I'm getting the OFX::UnsupportedFileError.  I dropped back to 0.3.3 and it still works. A short example of a downloaded text file:

```sh
"OFXHEADER:100\r\nDATA:OFXSGML\r\nVERSION:102\r\nSECURITY:NONE\r\nENCODING:USASCII\r\nCHARSET:1252\r\nCOMPRESSION:NONE\r\nOLDFILEUID:NONE\r\nNEWFILEUID:NONE\r\n\r\n<OFX>\r\n   <SIGNONMSGSRSV1>\r\n      <SONRS>\r\n         <STATUS>\r\n            <CODE>0\r\n            <SEVERITY>INFO\r\n         </STATUS>\r\n         <DTSERVER>20220910081143.727[-5:CDT]\r\n         <LANGUAGE>ENG\r\n         <FI>\r\n            <ORG>River Bank & Trust\r\n            <FID>52161\r\n         </FI>\r\n         <INTU.BID>52161\r\n         <INTU.USERID>xxxx@cccc\r\n      </SONRS>\r\n   </SIGNONMSGSRSV1>\r\n   <BANKMSGSRSV1>\r\n      <STMTTRNRS>\r\n         <TRNUID>0\r\n         <STATUS>\r\n            <CODE>0\r\n            <SEVERITY>INFO\r\n         </STATUS>\r\n         <STMTRS>\r\n            <CURDEF>USD\r\n            <BANKACCTFROM>\r\n               <BANKID>xxxxxx\r\n               <ACCTID>yyyyyyy\r\n               <ACCTTYPE>CHECKING\r\n            </BANKACCTFROM>\r\n            <BANKTRANLIST>\r\n               <DTSTART>20220901000000.000[-5:CDT]\r\n               <DTEND>20220910235959.000[-5:CDT]\r\n               <STMTTRN>\r\n                  <TRNTYPE>CREDIT\r\n                  <DTPOSTED>20220909000000.000\r\n                  <TRNAMT>603\r\n                  <FITID>63671357\r\n                  <NAME>VETERANS OF WARS PAYMENT\r\n                  <MEMO>Deposit VETERANS OF WARS PAYMENT\r\n               </STMTTRN>\r\n               <STMTTRN>\r\n                  <TRNTYPE>DEBIT\r\n                  <DTPOSTED>20220902000000.000\r\n                  <TRNAMT>-800\r\n                  <FITID>63406872\r\n                  <CHECKNUM>3706\r\n                  <NAME>CK # 3706\r\n                  <MEMO>On-Us Check CK # 3706\r\n               </STMTTRN>\r\n               <STMTTRN>\r\n                  <TRNTYPE>DEBIT\r\n                  <DTPOSTED>20220901000000.000\r\n                  <TRNAMT>-78\r\n                  <FITID>63356623\r\n                  <NAME>BP-AUTO OWNERS I BILL PAY\r\n                  <MEMO>On-Us Check BP-AUTO OWNERS I BILL PAY\r\n               </STMTTRN>\r\n            </BANKTRANLIST>\r\n            <LEDGERBAL>\r\n               <BALAMT>16819.07\r\n               <DTASOF>20220910081143.000[-5:CDT]\r\n            </LEDGERBAL>\r\n            <AVAILBAL>\r\n               <BALAMT>16819.07\r\n               <DTASOF>20220910081143.000[-5:CDT]\r\n            </AVAILBAL>\r\n         </STMTRS>\r\n      </STMTTRNRS>\r\n   </BANKMSGSRSV1>\r\n</OFX>\r\n"
```

If I try to parse it in a Rails console

```ruby
bs = BankStatement.find(52)
acct =  OFX(bs.ofx_data).account
```

I get an error:

```sh
/Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ofx-0.3.5/lib/ofx/parser.rb:15:in `rescue in initialize': OFX::UnsupportedFileError (OFX::UnsupportedFileError)                                        
/Users/salex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ofx-0.3.5/lib/ofx/parser.rb:13:in `initialize': undefined local variable or method `content' for #<OFX::Parser::Base:0x000000013d80ca30 @content="OFXHEADER:100\r\nDATA:OFXSGML\r\nVERSION:102\r\nSECURITY:NONE\r\nENCODING:USASCII\r\nCHARSET:1252\r\nCOMPRESSION:NONE\r\nOLDFILEUID:NONE\r\nNEWFILEUID:NONE\r\n\r\n<OFX>\r\n   <SIGNONMSGSRSV1>\r\n      <SONRS>\r\n         <STATUS>\r\n            <CODE>0\r\n            <SEVERITY>INFO\r\n         </STATUS>\r\n         <DTSERVER>20220910081143.727[-5:CDT]\r\n         <LANGUAGE>ENG\r\n         <FI>\r\n            <ORG>River Bank & Trust\r\n            <FID>52161\r\n         </FI>\r\n         <INTU.BID>52161\r\n         <INTU.USERID>wpp8600@qm14\r\n      </SONRS>\r\n   </SIGNONMSGSRSV1>\r\n   <BANKMSGSRSV1>\r\n      <STMTTRNRS>\r\n         <TRNUID>0\r\n         <STATUS>\r\n            <CODE>0\r\n            <SEVERITY>INFO\r\n         </STATUS>\r\n         <STMTRS>\r\n            <CURDEF>USD\r\n            <BANKACCTFROM>\r\n               <BANKID>062206567\r\n               <ACCTID>20011288\r\n               <ACCTTYPE>CHECKING\r\n            </BANKACCTFROM>\r\n            <BANKTRANLIST>\r\n               <DTSTART>20220901000000.000[-5:CDT]\r\n               <DTEND>20220910235959.000[-5:CDT]\r\n               <STMTTRN>\r\n                  <TRNTYPE>CREDIT\r\n                  <DTPOSTED>20220909000000.000\r\n                  <TRNAMT>603\r\n                  <FITID>63671357\r\n                  <NAME>VETERANS OF WARS PAYMENT\r\n                  <MEMO>Deposit VETERANS OF WARS PAYMENT\r\n               </STMTTRN>\r\n               <STMTTRN>\r\n                  <TRNTYPE>DEBIT\r\n                  <DTPOSTED>20220902000000.000\r\n                  <TRNAMT>-800\r\n                  <FITID>63406872\r\n                  <CHECKNUM>3706\r\n                  <NAME>CK # 3706\r\n                  <MEMO>On-Us Check CK # 3706\r\n               </STMTTRN>\r\n               <STMTTRN>\r\n                  <TRNTYPE>DEBIT\r\n                  <DTPOSTED>20220901000000.000\r\n                  <TRNAMT>-78\r\n                  <FITID>63356623\r\n                  <NAME>BP-AUTO OWNERS I BILL PAY\r\n                  <MEMO>On-Us Check BP-AUTO OWNERS I BILL PAY\r\n               </STMTTRN>\r\n            </BANKTRANLIST>\r\n            <LEDGERBAL>\r\n               <BALAMT>16819.07\r\n               <DTASOF>20220910081143.000[-5:CDT]\r\n            </LEDGERBAL>\r\n            <AVAILBAL>\r\n               <BALAMT>16819.07\r\n               <DTASOF>20220910081143.000[-5:CDT]\r\n            </AVAILBAL>\r\n         </STMTRS>\r\n      </STMTTRNRS>\r\n   </BANKMSGSRSV1>\r\n</OFX>\r\n"> (NameError)
Did you mean?  conten
               @content
```

Again, I have a working version, but something changed

**Comment by cesarjr** [comment]
Hi!

I tested your file with the latest commit and it worked on my machine. (Gosh! I tried to not write this sentence. Now I'm feeling like that guy of The IT Crowd series 😂).

Could you, please check it on you project?

```ruby
gem 'ofx', git: 'https://github.com/annacruz/ofx.git', ref: 'ee01638'
```

I hope it can help you.

**Comment by salex** [comment]
@cesarjr

That appears to work!

I guess there will be a version release at some point. I'm just glad someone is keeping it up to date. There does not seem to be a version/branches approach on the GitHub page, but it looks like someone it trying to work on it,

Thank you

**Comment by JoeDupuis** [comment]
As describe in #99 I think we should reopen this issue. The problem still exist on the rubygems version.

**Comment by cesarjr** [comment]
Hi @JoeDupuis !

I think @annacruz is preparing a new release and this problem is gonna be solved at RubyGems. Meanwhile a recommend you to use the latest commit in the repo. This is stable and we're using it in production in a big app.

Thanks to let us know.
